\echo Borrant les taules...
DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS sala CASCADE;
DROP TABLE IF EXISTS jornada CASCADE;
DROP TABLE IF EXISTS entrada CASCADE;
DROP TABLE IF EXISTS pais CASCADE;
DROP TYPE IF EXISTS gender CASCADE;
DROP TABLE IF EXISTS persona CASCADE;
DROP TABLE IF EXISTS jugador CASCADE;
DROP TABLE IF EXISTS jutge CASCADE;
DROP TABLE IF EXISTS partida CASCADE;
DROP TABLE IF EXISTS moviment CASCADE;
\echo taules borrades
