--TRIGGERS

CREATE OR REPLACE TRIGGER updateReferee 
	AFTER INSERT OR UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE update_game_referee();

CREATE OR REPLACE TRIGGER refereeControl 
	BEFORE INSERT OR UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE referee_control();

CREATE OR REPLACE TRIGGER update_ticket
	AFTER INSERT
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE update_ticket();
