--TRIGGERS

CREATE TRIGGER updateReferee 
	AFTER UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE update_game_referee();

CREATE TRIGGER refereeControl 
	BEFORE INSERT OR UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE referee_control();

CREATE TRIGGER update_ticket
	AFTER INSERT
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE updateTicket();
