--TRIGGERS

CREATE TRIGGER update_referee 
	AFTER INSERT OR UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE update_game_referee();

CREATE TRIGGER referee_control 
	BEFORE INSERT OR UPDATE
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE referee_control();

CREATE TRIGGER update_ticket
	AFTER INSERT
	ON partida FOR EACH ROW
	EXECUTE PROCEDURE update_ticket();
