DROP FUNCTION IF EXISTS arbitre_blanc();
DROP FUNCTION IF EXISTS arbitre_negre();
DROP FUNCTION IF EXISTS arbitre_taules();
DROP FUNCTION IF EXISTS entrades_disponibles(text,text, int);
DROP FUNCTION IF EXISTS guanyador_pais(paisEntrada text);
DROP FUNCTION IF EXISTS pais_guanyador();
DROP FUNCTION IF EXISTS guanyadors();
DROP FUNCTION IF EXISTS  partida_mes_curta();
DROP FUNCTION IF EXISTS  partida_mes_llarga();
DROP FUNCTION IF EXISTS informe_moviments(int, int);
